---

- name: nvidia-docker (v2) release key is registered
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: software-properties-common is installed for prerequisite for apt_repository ansible module
  apt:
    name: software-properties-common
    state: present

- name: Register distribution variable
  shell: ". /etc/os-release;echo $ID$VERSION_ID"
  register: distribution

- name: Add nvidia-docker (v2) apt repo
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/{{ item }}/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    mode: 0644
  with_items:
  - "{{ distribution.stdout_lines }}"
  notify: update apt cache

- name: Flush handlers
  meta: flush_handlers

- name: nvidia-docker (v1) is uninstalled
  apt:
    name: nvidia-docker
    state: absent

- name: confirm content of /etc/docker/daemon.json
  command: cat /etc/docker/daemon.json
  register: nvidia_docker_daemon_json_backup
  failed_when: False
  changed_when: False

# TODO: Automatically check dependencies of nvidia-docker
- name: nvidia-container-runtime (v2) is installed
  apt:
    name: "nvidia-container-runtime={{ nvidia_container_runtime_version }}+docker{{ nvidia_docker_docker_version }}-1"
    state: present
  notify: restart docker service

- name: nvidia-docker (v2) is installed
  apt:
    name: "nvidia-docker2={{ nvidia_docker_version }}+docker{{ nvidia_docker_docker_version }}-1"
    state: present
  notify: restart docker service

- name: confirm content of /etc/docker/daemon.json after installation of nvidia-docker2
  command: cat /etc/docker/daemon.json
  register: nvidia_docker_daemon_json_v2
  changed_when: False

- name: content of /etc/docker/daemon.json is merged
  copy:
    content: "{{ nvidia_docker_daemon_json_backup.stdout | from_json | combine(nvidia_docker_daemon_json_v2.stdout | from_json) }}"
    dest: /etc/docker/daemon.json
    validate: python -m json.tool %s
  when: nvidia_docker_daemon_json_backup.stdout != ""

- name: Make nvidia the default docker runtime
  copy:
    content: "{{ nvidia_docker_daemon_json_v2.stdout | from_json | combine({\"default-runtime\": \"nvidia\"}) }}"
    dest: /etc/docker/daemon.json
    validate: python -m json.tool %s
  when: make_nvidia_default_runtime
  notify: restart docker service
